### ISSUE TITLE
Are we 100% sure about this new way of fingerprinting?

### ISSUE THREAD

**Issue by ycamper** [fox-it/cisco-ios-xe-implant-detection#4]
So, out of curiosity, I downloaded and built openresty, and added the location configuration:

```
mark@bleep:~/.build/openresty/nginx$ cat conf/nginx.conf
worker_processes  1;
daemon off;
events {
    worker_connections  1024;
}

http {
    server {
        listen       9999;
        server_name  localhost;
         location ~* % {
            add_header Content-Type text/html;
            add_header Cache-Control 'no-cache, no-store, must-revalidate';
            add_header Pragma no-cache;
            add_header Strict-Transport-Security "max-age=3153600; includeSubdomains";
            return 404;
        }
        location / {
            root   html;
            index  index.html index.htm;
        }
    }
}
```

When I run openresty:
```
mark@bleep:~/.build/openresty/nginx$ ../bin/openresty -p `pwd` -c conf/nginx.conf`)
```

And curl the endpoint, I don't get those headers that are supposed to be added, I get the default openresty 404:

```
mark@bleep:~$ curl 'localhost:9999/%25' -vv
*   Trying 127.0.0.1:9999...
* Connected to localhost (127.0.0.1) port 9999 (#0)
> GET /%25 HTTP/1.1
> Host: localhost:9999
> User-Agent: curl/7.81.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Server: openresty/1.21.4.2
< Date: Wed, 25 Oct 2023 17:06:10 GMT
< Content-Type: text/html
< Content-Length: 159
< Connection: keep-alive
<
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>openresty/1.21.4.2</center>
</body>
</html>
* Connection #0 to host localhost left intact
```

I'm _guessing_ the headers aren't added because nginx doesn't want 404's to be cached? I don't really know, but that's beside the point (it sets those headers if you `return 200;`). If I remove this location statement, and my nginx config looks like this:

```
mark@bleep:~/.build/openresty/nginx$ cat conf/nginx.conf
worker_processes  1;
daemon off;
events {
    worker_connections  1024;
}

http {
    server {
        listen       9999;
        server_name  localhost;

        location / {
            root   html;
            index  index.html index.htm;
        }
    }
}
mark@bleep:~/.build/openresty/nginx$ ../bin/openresty -p `pwd` -c conf/nginx.conf
```

And curl that endpoint again:

```
mark@bleep:~$ curl 'localhost:9999/%25' -vv
*   Trying 127.0.0.1:9999...
* Connected to localhost (127.0.0.1) port 9999 (#0)
> GET /%25 HTTP/1.1
> Host: localhost:9999
> User-Agent: curl/7.81.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Server: openresty/1.21.4.2
< Date: Wed, 25 Oct 2023 17:07:54 GMT
< Content-Type: text/html
< Content-Length: 159
< Connection: keep-alive
<
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>openresty/1.21.4.2</center>
</body>
</html>
* Connection #0 to host localhost left intact
```

It's the same error. Could this be a red herring? I don't have direct access to any compromised machines, so I cannot verify anything; I want to make sure before releasing any numbers to the public.

Edit:

One thing that it could be is some other default 404 handler that these devices may have, which may differ,

**Comment by yunzheng** [comment]
Hi @ycamper, I see you already closed the issue. So wondering if you still have some questions :)

Regarding the HTTP headers not present when returning a 404 response, we can explain this by reading the official Nginx documentation here https://nginx.org/en/docs/http/ngx_http_headers_module.html:

> Adds the specified field to a response header provided that the response code equals 200, 201 (1.3.10), 204, 206, 301, 302, 303, 304, 307 (1.1.16, 1.0.13), or 308 (1.13.0).

Regarding the differences in 404 responses, we don't have the exact Nginx configuration of the Cisco devices, but it has a different 404 response (in plaintext) for pages it cannot find. You can test this against a non implanted device as well:

```shell
$ curl -k https://my-first-cisco-without-implant/hello
404 Not Found

$ curl -k https://my-first-cisco-without-implant/hello%25
404 Not Found
```

Like you said, most likely a custom 404 handler (probably in Lua). And when the implant config is present, it goes to the default Nginx handler when it hits the any percent and does a `return 404`:

```shell
$ curl -k http://my-cisco-with-implant/hello
404 Not Found

$ curl -k http://my-cisco-with-implant/hello%25
<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```
